### Liste des livres
GET http://localhost:8080/api/books

### Un livre par id
GET http://localhost:8080/api/books?id=1

### Créer un livre
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Domain-Driven Design",
  "author": "Eric Evans",
  "pages": 560
}

### Modifier un livre
PUT http://localhost:8080/api/books?id=1
Content-Type: application/json

{
  "title": "1984 (Updated)",
  "author": "George Orwell",
  "pages": 330
}

### Supprimer un livre
DELETE http://localhost:8080/api/books?id=2